name: backer-master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install cnpm
      run: npm i -g cnpm

    - name: Install dependencies
      run: cnpm i 

    - name: Build weapp
      run: yarn start:prod

    - name: Generate private key for upload
      run: echo "$BACKERSECRET" > private.key
      env:
        BACKERSECRET: ${{ secrets.BACKERSECRET }}